### PR TITLE
Fix data abort due to unaligned access in Zynq QSPI driver

### PR DESCRIPTION
**Pull request by jacobmcnamee**
/cc @swift-nav/firmware

### CODE REVIEW

**Comment by mbavaro** [comment]
My goodness... I agree that original code it's tough. 
So the only weird case is for size 3 I guess.. it's like they assume a 32-bit unsigned could be packed into something not quite exactly like a little endian? Could that be due to some special byte ordering reading from QSPI 32-bit values at 16-bit boundaries? And somehow the compiler doing >>16 should pick the right byte? Sorry, baffled.

**Comment by jacobmcnamee** [comment]
Bench tested to fix abort in `image_set write` and to successfully boot.

**Comment by jacobmcnamee** [comment]
It should all be little-endian. I have no idea why they decided to copy three bytes as `u16` + `u8` accesses, but the memcpy should be equivalent regardless.

**Comment by mbavaro** [comment]
I seem to remember regardless of endiannes, the compiler >> on unsigned integers always behaves the same, but memcpy() wouldn't. So if data are coming from QSPI in a strange order some mangling might be necessary.. having said that the original code is awful >:| 
Since we know we live in a little-endian World your memcpy() will be much more elegant, readable and resilient to errors.

**Pull request merged**
